from src.model import MultiScaleConv3dEPBModelConfig

epb_psz128_all_in_one_wo_lset_model_medium = MultiScaleConv3dEPBModelConfig(
    hidden_dim=32,
    atom_type_num=153,
    reaction_size=9,
    patch_size=128,
    lvlset_embed_scale=10,
    lvlset_embed_theta=10000,
    charge_embed_scale=1000,
    charge_embed_theta=10000,
    kernel_sizes=[1, 5, 7],
    embed_dim_scale=4,
    dropout_rate=0.1,
    block_drop_rate=0.1,
    use_lset=False,
    is_atom_wise_potential_trained=True,
    output_kernel_size=5,
    reaction_field_mapping_version="u-net",
)

epb_psz64_ctx32_all_in_one_wo_lset_model_medium = MultiScaleConv3dEPBModelConfig(
    hidden_dim=32,
    atom_type_num=153,
    reaction_size=9,
    patch_size=128,
    lvlset_embed_scale=10,
    lvlset_embed_theta=10000,
    charge_embed_scale=1000,
    charge_embed_theta=10000,
    kernel_sizes=[1, 5, 7],
    embed_dim_scale=4,
    dropout_rate=0.1,
    block_drop_rate=0.1,
    use_lset=False,
    is_atom_wise_potential_trained=True,
    output_kernel_size=5,
    reaction_field_mapping_version="u-net",
)

epb_psz64_ctx32_all_in_one_with_lset_model_medium = MultiScaleConv3dEPBModelConfig(
    hidden_dim=32,
    atom_type_num=153,
    reaction_size=9,
    patch_size=128,
    lvlset_embed_scale=10,
    lvlset_embed_theta=10000,
    charge_embed_scale=1000,
    charge_embed_theta=10000,
    kernel_sizes=[1, 5, 7],
    embed_dim_scale=4,
    dropout_rate=0.1,
    block_drop_rate=0.1,
    use_lset=True,
    is_atom_wise_potential_trained=True,
    output_kernel_size=5,
    reaction_field_mapping_version="u-net",
)

epb_psz16_ctx56_all_in_one_wo_lset_model_medium = MultiScaleConv3dEPBModelConfig(
    hidden_dim=32,
    atom_type_num=153,
    reaction_size=9,
    patch_size=128,
    lvlset_embed_scale=10,
    lvlset_embed_theta=10000,
    charge_embed_scale=1000,
    charge_embed_theta=10000,
    kernel_sizes=[1, 5, 7],
    embed_dim_scale=4,
    dropout_rate=0.1,
    block_drop_rate=0.1,
    use_lset=False,
    is_atom_wise_potential_trained=True,
    output_kernel_size=1,
    reaction_field_mapping_version="u-net",
)
