from src.model import MultiScaleAtomicEPBModelConfig, PBGNNConfig


wo_lset_model = MultiScaleAtomicEPBModelConfig(
    hidden_dim=128,
    embed_dim_scale=1,
    use_lset=False,
    is_atom_wise_potential_trained=True,
    reaction_field_mapping_version="pbgnn",
    pbgnn_config=PBGNNConfig(
        cutoff=5.0,
        n_atom_basis=64,
        n_interactions=3,
        radial_basis="GaussianRBF",
        activation="shifted_softplus",
        neighbor_list_cutoff=5.0,
    ),
)

model_medium = MultiScaleAtomicEPBModelConfig(
    hidden_dim=128,
    embed_dim_scale=1,
    charge_embed_scale=1e4,
    lvlset_embed_scale=1e4,
    use_lset=False,
    is_atom_wise_potential_trained=True,
    reaction_field_mapping_version="pbgnn",
    pbgnn_config=PBGNNConfig(
        cutoff=30.0,
        n_atom_basis=128,
        n_rbf=128,
        n_interactions=5,
        radial_basis="GaussianRBF",
        activation="shifted_softplus",
        neighbor_list_cutoff=10.0,
        max_num_neighbors=16,
        natom_threshold_for_max_num_neighbors=30000,
        conv_split_size=65536,
        use_gradient_checkpointing=True,
    ),
    use_shallow_embedding=True,
)

fusion_model_medium = MultiScaleAtomicEPBModelConfig(
    hidden_dim=128,
    embed_dim_scale=1,
    charge_embed_scale=1e4,
    lvlset_embed_scale=1e4,
    use_lset=True,
    is_atom_wise_potential_trained=True,
    reaction_field_mapping_version="pbgnn",
    pbgnn_config=PBGNNConfig(
        cutoff=30.0,
        n_atom_basis=128,
        n_rbf=128,
        n_interactions=5,
        radial_basis="GaussianRBF",
        activation="shifted_softplus",
        neighbor_list_cutoff=10.0,
        max_num_neighbors=16,
        natom_threshold_for_max_num_neighbors=30000,
        conv_split_size=65536,
        use_gradient_checkpointing=True,
    ),
    use_shallow_embedding=True,
)

model_small = MultiScaleAtomicEPBModelConfig(
    hidden_dim=128,
    embed_dim_scale=1,
    charge_embed_scale=1e4,
    lvlset_embed_scale=1e4,
    use_lset=False,
    is_atom_wise_potential_trained=True,
    reaction_field_mapping_version="pbgnn",
    pbgnn_config=PBGNNConfig(
        cutoff=30.0,
        n_atom_basis=128,
        n_rbf=256,
        n_interactions=5,
        radial_basis="GaussianRBF",
        activation="shifted_softplus",
        neighbor_list_cutoff=30.0,
        max_num_neighbors=16,
        natom_threshold_for_max_num_neighbors=30000,
        conv_split_size=65536,
        use_gradient_checkpointing=False,
    ),
    use_shallow_embedding=True,
)

fusion_model_small = MultiScaleAtomicEPBModelConfig(
    hidden_dim=128,
    embed_dim_scale=1,
    charge_embed_scale=1e4,
    lvlset_embed_scale=1e4,
    use_lset=True,
    is_atom_wise_potential_trained=True,
    reaction_field_mapping_version="pbgnn_fusion",
    pbgnn_config=PBGNNConfig(
        cutoff=30.0,
        n_atom_basis=128,
        n_rbf=256,
        n_interactions=5,
        radial_basis="GaussianRBF",
        activation="shifted_softplus",
        neighbor_list_cutoff=30.0,
        max_num_neighbors=16,
        natom_threshold_for_max_num_neighbors=30000,
        conv_split_size=65536,
        use_gradient_checkpointing=False,
    ),
    use_shallow_embedding=True,
)

bndy_fusion_model_small = MultiScaleAtomicEPBModelConfig(
    hidden_dim=128,
    embed_dim_scale=1,
    charge_embed_scale=1e4,
    lvlset_embed_scale=1e4,
    use_lset=True,
    is_atom_wise_potential_trained=True,
    reaction_field_mapping_version="pbgnn_bndy_fusion",
    pbgnn_config=PBGNNConfig(
        cutoff=30.0,
        n_atom_basis=128,
        n_rbf=256,
        n_interactions=5,
        radial_basis="GaussianRBF",
        activation="shifted_softplus",
        neighbor_list_cutoff=30.0,
        max_num_neighbors=16,
        natom_threshold_for_max_num_neighbors=30000,
        conv_split_size=65536,
        use_gradient_checkpointing=False,
    ),
    use_shallow_embedding=True,
    use_boundary_charge=True,
    use_boundary_lset=True,
)
